---
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/repo/repo.{{ ansible_facts['os_family'] }}.yml"
  tags:
    - repo
    - agent.install
    - server.install
    - proxy.install

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ zabbix_function }}/install_zabbix_{{ zabbix_function }}.{{ ansible_facts['os_family'] }}.yml"
  tags:
    - agent.install
    - server.install
    - proxy.install

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ zabbix_function }}/config_zabbix_{{ zabbix_function }}.{{ ansible_facts['os_family'] }}.yml"
  tags:
    - proxy.install
    - server.install
    - proxy.config
    - server.config
    - agent.install
    - agent.config

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/zabbix_add_host.yml"
  when: zabbix_function == 'agent'
  tags:
    - add.host

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/proxy/zabbix_add_proxy.yml"
  when: zabbix_function == 'proxy'
  tags:
    - proxy.add

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/userparam.yml"
  when: userparam is defined
  tags:
    - userparam

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/server/external_script.yml"
  when: external_script is defined
  tags:
    - externalScript
