---
- name: Configure zabbix agent
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: "0644"
  notify: restart agent
  tags:
    - agent.config
    - agent.install
