---
- name: Create a new host or update an existing host's info
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_fqdn }}"
    visible_name: "{{ ansible_hostname }}"
    host_groups:
      - "{{ ansible_system }} servers"
    link_templates:
      - "Template OS {{ ansible_system }}"
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ ansible_fqdn }}"
        port: 10050
  delegate_to: zabbix-api
  become: false
  tags:
    - agent.install
    - add.host
