---
- name: Create external scripts directory
  ansible.builtin.file:
    path: "{{ external_script_dir | default('/usr/lib/zabbix/externalscripts/') }}"
    state: directory
  notify: rebuild
  tags: externalScript

- name: Copy external script to server
  ansible.builtin.copy:
    src: "{{ external_dir }}/{{ item.script }}"
    dest: "{{ external_script_dir | default('/usr/lib/zabbix/externalscripts/') }}/{{ item.script }}"
    owner: zabbix
    group: zabbix
    mode: "0700"
    backup: yes
  loop: "{{ external_script }}"
  tags: externalScript
