---
- name: Install MariaDB for server
  ansible.builtin.include_role:
    name: ansible-mysql
  vars:
    mysql_root_db_pass: "{{ db_pass }}"
    mysql_db:
      - name: "{{ zabbix_db }}"
    mysql_users:
      - name: "{{ zabbix_user }}"
        pass: "{{ zabbix_pass }}"
        priv: "*.*:ALL"
  when: db_backend == "mysql"
  tags:
    - server.install

- name: Install zabbix server packages
  ansible.builtin.dnf:
    name:
      - "zabbix-server-{{ db_backend }}"
      - "zabbix-web-{{ db_backend }}"
      - zabbix-apache-conf
      - zabbix-sql-scripts
    state: present
  tags:
    - server.install

- name: Check if schema has already been imported
  ansible.builtin.stat:
    path: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  register: schema_file
  changed_when: false
  tags:
    - server.install

- name: Import Zabbix server database schema
  community.mysql.mysql_db:
    name: "{{ zabbix_db }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_pass }}"
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  failed_when: false
  when: schema_file.stat.exists
  tags:
    - server.install
