---

- name: Create a new proxy or update an existing proxies info
  community.zabbix.zabbix_proxy:
    proxy_name: "{{ ansible_fqdn }}"
    description: "{{ ansible_hostname }}"
    status: "{{ proxyMode }}"
    state: present
    interface:
      type: 0
      main: 1
      useip: 1
      ip: "{{ ansible_default_ipv4.address }}"
      dns: "{{ ansible_fqdn }}"
      port: 10050
  delegate_to: zabbix-api
  become: false
  tags:
    - proxy.install
    - proxy.add