---

- name: Create a new proxy or update an existing proxies info
  community.zabbix.zabbix_proxy:
    proxy_name: "{{ ansible_fqdn }}"
    description: "{{ ansible_hostname }}"
    status: "{{ proxyMode }}"
    state: present
  when: zabbix_function == 'proxy'
  delegate_to: zabbix-api
  become: false
  tags:
    - proxy.add