---
- name: Install Zabbix repo RPM for RedHat
  ansible.builtin.dnf:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-latest.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: false
  register: zabbix_repo_install
  tags:
    - repo
    - agent.install
    - server.install
    - proxy.install

- name: Clean dnf cache after repo install
  ansible.builtin.command: dnf clean all
  changed_when: false
  when: zabbix_repo_install.changed
  tags:
    - repo
    - agent.install
    - server.install
    - proxy.install
